In [1]:
import pandas as pd

In [2]:
ev= pd.read_csv('evaluation_trades.csv')

In [5]:
ev

,Entry Time,Exit Time,Type,Entry Price,Exit Price,PnL,Return,Duration
0,2011-05-08 18:00:00,2011-05-09 16:00:00,Short,1.43527,1.43111,0.003874,0.002699,22
1,2011-05-09 18:00:00,2011-05-10 16:00:00,Short,1.43364,1.43539,-0.002037,-0.001421,22
2,2011-05-10 18:00:00,2011-05-11 16:00:00,Short,1.43942,1.42188,0.017256,0.011988,22
3,2011-05-11 18:00:00,2011-05-12 16:00:00,Short,1.41937,1.42319,-0.004105,-0.002892,22
4,2011-05-12 18:00:00,2011-05-13 16:00:00,Short,1.42278,1.41037,0.012128,0.008524,22
...,...,...,...,...,...,...,...,...
78,2011-07-12 18:00:00,2011-07-12 19:00:00,Short,1.40270,1.39714,0.005281,0.003765,1
79,2011-07-12 19:00:00,2011-07-12 22:00:00,Long,1.39714,1.39697,-0.000449,-0.000322,3
80,2011-07-12 22:00:00,2011-07-13 08:00:00,Short,1.39697,1.40634,-0.009651,-0.006909,10
81,2011-07-13 08:00:00,2011-07-13 13:00:00,Long,1.40634,1.40460,-0.002021,-0.001437,5
82,2011-07-13 18:00:00,2011-07-13 21:00:00,Short,1.41442,1.42370,-0.009565,-0.006762,3

In [7]:
com=pd.read_csv('final_combined_dataset.csv')
com

,Time,Ren_Value,Blue,Red,dir,Yellow,Blue/Yellow,Red/Yellow,Frac_Value,Flag,...,enriched_91,enriched_92,enriched_93,enriched_94,enriched_95,enriched_96,enriched_97,enriched_98,enriched_99,action
0,2010-07-15 01:00:00,1.27091,0,1,1,0,0,0,1.27779,0.0,...,-0.016782,0.045043,0.018265,-0.002483,-0.032974,-0.038779,0.015469,-0.079812,0.006390,0
1,2010-07-15 02:00:00,1.27091,0,1,1,0,0,0,1.27779,0.0,...,-0.010932,0.054204,0.008405,0.035053,-0.036290,-0.044272,0.045164,-0.088385,-0.000926,0
2,2010-07-15 03:00:00,1.27091,0,1,1,0,0,0,1.27779,0.0,...,0.010186,0.054300,0.005771,0.001164,-0.053966,-0.048695,0.015579,-0.091382,0.000890,0
3,2010-07-15 04:00:00,1.27091,0,1,1,0,0,0,1.27779,0.0,...,0.047847,0.014266,-0.015653,0.011796,-0.030571,-0.007509,-0.008914,-0.045432,-0.013324,0
4,2010-07-15 05:00:00,1.27091,0,1,1,0,0,0,1.27779,0.0,...,-0.055061,0.037791,-0.015133,0.041477,-0.006587,-0.020886,0.010574,-0.169811,-0.023679,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6977,2011-07-13 19:00:00,1.41714,1,0,0,0,0,0,1.41920,0.0,...,0.013319,0.031646,-0.002470,0.031049,-0.033658,-0.020882,0.024091,-0.086371,0.000290,0
6978,2011-07-13 20:00:00,1.41714,1,0,0,0,0,0,1.41920,0.0,...,-0.034864,-0.016235,0.035849,0.070053,-0.059074,0.009314,0.060580,-0.080554,0.002477,0
6979,2011-07-13 21:00:00,1.42370,1,0,0,0,0,0,1.41920,0.0,...,-0.049825,0.048452,-0.025987,-0.003939,-0.044290,-0.066194,0.014955,-0.212346,-0.038822,0
6980,2011-07-13 22:00:00,1.42370,1,0,0,0,0,0,1.41920,0.0,...,0.014013,0.061951,-0.015372,0.006790,-0.085849,-0.084729,0.034507,-0.112005,-0.027699,0
6981,2011-07-13 23:00:00,1.42370,1,0,0,0,0,0,1.41920,0.0,...,0.004307,0.027706,0.011410,0.005832,-0.096712,-0.065557,0.010157,-0.099697,-0.045486,0

In [11]:
.\env\python.exe run_pipeline.py --mode aggregate --use-ib --instrument EURUSD --granularity H1 --ib-port 7497

SyntaxError: invalid syntax (1503129287.py, line 1)